const cartActionTypes={
    TOGGLE_CART_HIDDEN:"TOGGLE_CART_HIDDEN",
    ADD_CART_ITEMS:"ADD_CART_ITEMS",
    CLEAR_ITEM_CART:"CLEAR_ITEM_CART",
    REMOVE_CART_ITEM:"REMOVE_CART_ITEM"
}

export default  cartActionTypes